module.exports = {
  ACTIVITY_TRACKER_EVENTS: Object.freeze({
    // ========== PROJECT CONTROLLER EVENTS ==========
    CREATE_PROJECT: "CREATE_PROJECT",
    UPDATE_PROJECT: "UPDATE_PROJECT",
  }),

  SERVICE_TRACKER_EVENTS: Object.freeze({
    // ========== INTERNAL CONTROLLER EVENTS ==========
    DELETE_INACTIVE_USERS: "DELETE_INACTIVE_USERS",
    
    // ========== SYNC EVENTS ==========
    SYNC_USER_DATA: "SYNC_USER_DATA", 
    SYNC_ADMIN_DATA: "SYNC_ADMIN_DATA",
    SYNC_MY_DATA: "SYNC_MY_DATA",
    
    // ========== SYSTEM EVENTS ==========
    CREATE_SUPER_ADMIN: "CREATE_SUPER_ADMIN",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER_DETAILS: "UPDATE_USER_DETAILS",
    UPDATE_ADMIN_DETAILS: "UPDATE_ADMIN_DETAILS"
  })
};